### ISSUE TITLE
could we use googlesheets to store network-wide tokens?

### ISSUE THREAD

**Issue by almartin82** [publicprep/Rppn#2]
storing one-off or shared keys in a google sheet could let us keep this package public, but keep tight control over key sharing.  thanks @chrishaid for the idea.

**Comment by chrishaid** [comment]
For your reference:  here's the logic for using @jennybc's googlesheets in production:
https://github.com/chrishaid/idea2/blob/master/cron/jobs/recruiting/recruiting.R
